apiVersion: kops.kops.crossplane.io/v1alpha1
kind: Kops
metadata:
  name: dor-test-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  forProvider:
    stateBucket: s3://runai-kops-state
    domain: runailabs.com
    region: us-east-1
    clusterSpec:
      sshKeyName: "runai-dev"
      kubeAPIServer:
        oidcClientID: runai
        oidcIssuerURL: https://app.run.ai/auth/realms/envinaclick
        oidcUsernamePrefix: "-" 
      api:
        loadBalancer:
          class: Classic
          type: Public
          idleTimeoutSeconds: 300
      authorization:
        rbac: {}
      containerRuntime: docker
      nonMasqueradeCIDR: 10.0.0.0/8
      cloudProvider: aws
      iam:
        legacy: false
      etcdClusters:
      - name: main
        provider: Manager
        cpuRequest: 200m
        etcdMembers:
        - encryptedVolume: true
          instanceGroup: master
          name: master
        memoryRequest: 100Mi
      kubelet:
        anonymousAuth: false
      kubernetesAPIAccess:
      - 0.0.0.0/0
      - ::/0
      kubernetesVersion: 1.23.9
      networkCIDR: 172.20.0.0/16
      subnets:
      - cidr: 172.20.32.0/19
        name: "us-east-1a"
        type: Public
        zone: "us-east-1a"
      topology:
        dns:
          type: Public
        masters: public
        nodes: public
    instanceGroupSpec:
    - image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
      instanceMetadata:
        httpPutResponseHopLimit: 3
        httpTokens: required
      machineType: t3.large
      maxSize: 1
      minSize: 1
      nodeLabels:
        kops.k8s.io/instancegroup: master
      role: Master
      subnets:
      - "us-east-1a"
    - image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
      machineType: m5.xlarge
      maxSize: 2
      minSize: 2
      nodeLabels:
        kops.k8s.io/instancegroup: nodes
        nvidia.com/gpu.deploy.device-plugin: "true"
        nvidia.com/gpu.deploy.dcgm-exporter: "true"
      role: Node
      subnets:
      - "us-east-1a"
  writeConnectionSecretToRef:
    namespace: default
    name: dor-test-kubeconfig
  providerConfigRef:
    name: example